app = 'evopt'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[http_service]
internal_port = 7050
force_https = true
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 2
